from django.urls import path

from .views import crud, database, export_data, general, import_data, merge, replace


urlpatterns = [
    path('', general.index, name='index'),
    path('error', general.error, name='error'),
    path('import/notoria/', import_data.import_notoria, name='import_notoria'),
    path('import/stooq/', import_data.import_stooq, name='import_stooq'),
    path('import/gpw/', import_data.import_gpw, name='import_gpw'),
    path('import/replace_data', replace.replace_data, name='replace_data'),
    path('import/replace_data_multiple', replace.replace_data_multiple, name='replace_data_multiple'),
    path('import/insert_data', replace.insert_data, name='insert_data'),
    path('export', export_data.export, name='export'),
    path('manage/home', general.manage, name='manage_home'),
    path('manage/merge_data', merge.merge_data, name='merge_data'),
    path('manage/delete_data', merge.delete_data, name='delete_data'),
    path('manage/databaseExport', database.export_database, name='export_database'),
    path('manage/databaseImport', database.import_database, name='import_database'),
    path('manage/replace_database', database.replace_database, name='replace_database'),

    path('manage/companies', crud.CompanyView.as_view(), name='companies'),
    path('manage/companies/create', crud.CompanyCreateView.as_view(), name='create_company'),
    path('manage/companies/update/<int:pk>', crud.CompanyUpdateView.as_view(), name='update_company'),
    path('manage/companies/delete/<int:pk>', crud.CompanyDeleteView.as_view(), name='delete_company'),
    path('manage/companies/merge', merge.CompanyMergeView.as_view(), name='merge_company'),
    path('manage/assets', crud.AssetsView.as_view(), name='assets'),
    path('manage/assets/create', crud.AssetsCreateView.as_view(), name='create_assets'),
    path('manage/assets/update/<int:pk>', crud.AssetsUpdateView.as_view(), name='update_assets'),
    path('manage/assets/delete/<int:pk>', crud.AssetsDeleteView.as_view(), name='delete_assets'),
    path('manage/assetsCategories', crud.AssetsCategoryView.as_view(), name='assets_categories'),
    path('manage/assetsCategories/create', crud.AssetsCategoryCreateView.as_view(), name='create_assets_category'),
    path('manage/assetsCategories/update/<int:pk>', crud.AssetsCategoryUpdateView.as_view(), name='update_assets_category'),
    path('manage/assetsCategories/delete/<int:pk>', crud.AssetsCategoryDeleteView.as_view(), name='delete_assets_category'),
    path('manage/duPont', crud.DuPontIndicatorView.as_view(), name='dupont'),
    path('manage/duPont/create', crud.DuPontIndicatorCreateView.as_view(), name='create_dupont'),
    path('manage/duPont/update/<int:pk>', crud.DuPontIndicatorUpdateView.as_view(), name='update_dupont'),
    path('manage/duPont/delete/<int:pk>', crud.DuPontIndicatorDeleteView.as_view(), name='delete_dupont'),
    path('manage/ekdClasses', crud.EkdClassView.as_view(), name='ekd_classes'),
    path('manage/ekdClasses/create', crud.EkdClassCreateView.as_view(), name='create_ekd_class'),
    path('manage/ekdClasses/update/<int:pk>', crud.EkdClassUpdateView.as_view(), name='update_ekd_class'),
    path('manage/ekdClasses/delete/<int:pk>', crud.EkdClassDeleteView.as_view(), name='delete_ekd_class'),
    path('manage/ekdSections', crud.EkdSectionView.as_view(), name='ekd_sections'),
    path('manage/ekdSections/create', crud.EkdSectionCreateView.as_view(), name='create_ekd_section'),
    path('manage/ekdSections/update/<int:pk>', crud.EkdSectionUpdateView.as_view(), name='update_ekd_section'),
    path('manage/ekdSections/delete/<int:pk>', crud.EkdSectionDeleteView.as_view(), name='delete_ekd_section'),
    path('manage/equityLiabilities', crud.EquityLiabilitiesView.as_view(), name='equity_liabilities'),
    path('manage/equityLiabilities/create', crud.EquityLiabilitiesCreateView.as_view(), name='create_equity_liabilities'),
    path('manage/equityLiabilities/update/<int:pk>', crud.EquityLiabilitiesUpdateView.as_view(), name='update_equity_liabilities'),
    path('manage/equityLiabilities/delete/<int:pk>', crud.EquityLiabilitiesDeleteView.as_view(), name='delete_equity_liabilities'),
    path('manage/equityLiabilitiesCategories', crud.EquityLiabilitiesCategoryView.as_view(), name='equity_liabilities_categories'),
    path('manage/equityLiabilitiesCategories/create', crud.EquityLiabilitiesCategoryCreateView.as_view(), name='create_equity_liabilities_category'),
    path('manage/equityLiabilitiesCategories/update/<int:pk>', crud.EquityLiabilitiesCategoryUpdateView.as_view(), name='update_equity_liabilities_category'),
    path('manage/equityLiabilitiesCategories/delete/<int:pk>', crud.EquityLiabilitiesCategoryDeleteView.as_view(), name='delete_equity_liabilities_category'),
    path('manage/financial', crud.FinancialRatiosView.as_view(), name='financial'),
    path('manage/financial/create', crud.FinancialRatiosCreateView.as_view(), name='create_financial'),
    path('manage/financial/update/<int:pk>', crud.FinancialRatiosUpdateView.as_view(), name='update_financial'),
    path('manage/financial/delete/<int:pk>', crud.FinancialRatiosDeleteView.as_view(), name='delete_financial'),
    path('manage/market', crud.MarketValueView.as_view(), name='market'),
    path('manage/market/create', crud.MarketValueCreateView.as_view(), name='create_market'),
    path('manage/market/update/<int:pk>', crud.MarketValueUpdateView.as_view(), name='update_market'),
    path('manage/market/delete/<int:pk>', crud.MarketValueDeleteView.as_view(), name='delete_market'),
    path('manage/stock', crud.StockQuoteView.as_view(), name='stock'),
    path('manage/stock/create', crud.StockQuoteCreateView.as_view(), name='create_stock'),
    path('manage/stock/update/<int:pk>', crud.StockQuoteUpdateView.as_view(), name='update_stock'),
    path('manage/stock/delete/<int:pk>', crud.StockQuoteDeleteView.as_view(), name='delete_stock')
]
