# Generated by Django 3.0.8 on 2020-07-16 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='EKD_Class',
        ),
        migrations.DeleteModel(
            name='EKD_Section',
        ),
    ]
